//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_SkrylevaLiana320.DBconnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
       
        public Faculty()
        {
            this.Department = new HashSet<Department>();
        }
    
        public string abbr { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Department> Department { get; set; }
    }
}
